# Generated by Django 3.1.4 on 2020-12-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='image',
            new_name='url',
        ),
        migrations.RenameField(
            model_name='productsize',
            old_name='quantity',
            new_name='count',
        ),
        migrations.RemoveField(
            model_name='productsize',
            name='is_main',
        ),
        migrations.AddField(
            model_name='productimage',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
