# Generated by Django 3.1.4 on 2020-12-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20201224_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'Men'), ('w', 'Women'), ('k', 'Kids')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='label',
            field=models.CharField(blank=True, choices=[('sale', 'Sale'), ('new', 'New'), ('hot', 'Hot')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='season',
            field=models.CharField(choices=[('w', 'Winter'), ('s', 'Summer'), ('sf', 'Spring/Fall'), ('ms', 'Multi Season')], max_length=12),
        ),
    ]
