# Generated by Django 3.1.4 on 2020-12-24 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20201224_1624'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
    ]
