# Generated by Django 3.1.4 on 2021-01-12 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_auto_20210112_1013'),
        ('product', '0006_remove_product_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='collection',
            field=models.ForeignKey(default='MEN', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='collection.collection'),
            preserve_default=False,
        ),
    ]
