# Generated by Django 3.0.5 on 2020-05-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscriber',
            field=models.BooleanField(default=True),
        ),
    ]
