# Generated by Django 3.0.5 on 2020-04-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='media/images/accounts/profile_images', verbose_name='Фото'),
        ),
    ]
