# Generated by Django 3.0.5 on 2020-05-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200503_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активний'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Визначає, чи може користувач заходити в дану адмінку.', verbose_name='Персонал'),
        ),
        migrations.AlterField(
            model_name='user',
            name='subscriber',
            field=models.BooleanField(default=True, verbose_name='Підписник'),
        ),
    ]
