# Generated by Django 3.0.5 on 2020-05-03 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200503_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Man'), (1, 'Woman'), (2, 'Kid')], null=True),
        ),
    ]
