# Generated by Django 3.0.5 on 2020-05-03 12:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Назва')),
                ('main_image', models.ImageField(blank=True, default='images/not-found.png', upload_to='images/categories/', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Назва')),
                ('description', models.TextField(blank=True, verbose_name='Описання')),
                ('main_image', models.ImageField(default='images/not-found.png', upload_to='images/products/main_images/', verbose_name='Основна картинка')),
                ('quantity', models.PositiveIntegerField(default=5, null=True, verbose_name='Кількість')),
                ('collection', models.PositiveSmallIntegerField(choices=[(0, 'Winter'), (1, 'Summer'), (2, 'Spring/Fall'), (3, 'Multi Season')], verbose_name='Колекція')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Поточна ціна')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стара ціна (до знижки)')),
                ('gender', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Men'), (1, 'Women'), (2, 'Kids')], null=True, verbose_name='Стать')),
                ('size', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Extra Small'), (1, 'Small'), (2, 'Medium'), (3, 'Large'), (4, 'Extra Large'), (5, 'Two Extra Large')], null=True, verbose_name='Розмір даної одиниці')),
                ('extra', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Sale'), (1, 'New'), (2, 'Hot')], null=True, verbose_name='Мітка')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.Category', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукти',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='No Image', upload_to='images/products/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.Product')),
            ],
            options={
                'verbose_name': 'Додаткова картинка',
                'verbose_name_plural': 'Додаткові картинки',
            },
        ),
    ]
