# Generated by Django 3.0.5 on 2020-04-22 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Назва')),
                ('main_image', models.ImageField(blank=True, default='images/not-found.png', upload_to='images/categories/', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Назва')),
                ('description', models.TextField(blank=True, verbose_name='Описання')),
                ('main_image', models.ImageField(default='images/not-found.png', upload_to='images/products/main_images/', verbose_name='Основна картинка')),
                ('quantity', models.PositiveIntegerField(default=5, null=True, verbose_name='Кількість')),
                ('collection', models.CharField(choices=[('w', 'Winter'), ('s', 'Summer'), ('s/f', 'Spring/Fall'), ('mlt', 'Multi')], max_length=3, verbose_name='Колекція')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Поточна ціна')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стара ціна (до знижки)')),
                ('gender', models.CharField(blank=True, choices=[('men', 'Men'), ('women', 'Women'), ('kids', 'Kids')], max_length=5, verbose_name='Стать')),
                ('size', models.CharField(blank=True, choices=[('xs', 'Extra Small'), ('s', 'Small'), ('m', 'Medium'), ('l', 'Large'), ('xl', 'Extra Large'), ('xxl', 'Two Extra Large')], max_length=3, verbose_name='Розмір даної одиниці')),
                ('product_extra', models.CharField(blank=True, choices=[('sale', 'Sale'), ('new', 'New'), ('hot', 'Hot')], max_length=5, verbose_name='Мітка')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.Category', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукти',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='No Image', upload_to='images/products/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.Product')),
            ],
            options={
                'verbose_name': 'Додаткова картинка',
                'verbose_name_plural': 'Додаткові картинки',
            },
        ),
    ]
