# Generated by Django 3.0.5 on 2020-05-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Men'), (1, 'Women'), (2, 'Kid')], null=True, verbose_name='Стать'),
        ),
    ]
