# Generated by Django 3.0.5 on 2020-04-11 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
                ('description', models.TextField(blank=True)),
                ('main_image', models.ImageField(upload_to='images/products/main_images/')),
                ('old_price', models.PositiveIntegerField(blank=True, null=True)),
                ('new_price', models.PositiveIntegerField()),
                ('size', models.CharField(choices=[('xs', 'Extra Small'), ('s', 'Small'), ('m', 'Medium'), ('l', 'Large'), ('xl', 'Extra Large'), ('xxl', 'Two Extra Large')], max_length=3)),
                ('quantity', models.PositiveIntegerField(default=5, null=True)),
                ('season', models.CharField(choices=[('w', 'Зима'), ('s', 'Літо'), ('s/f', 'Весна/Осінь')], max_length=3)),
                ('product_extra', models.CharField(blank=True, choices=[('sale', 'Sale'), ('new', 'New'), ('hot', 'Hot')], max_length=5)),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукти',
            },
        ),
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='category',
            name='main_image',
            field=models.ImageField(blank=True, upload_to='images/categories/', verbose_name='Картинка'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='No Image', upload_to='images/products/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.Product')),
            ],
            options={
                'verbose_name': 'Картинка',
                'verbose_name_plural': 'Картинки',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.Category', verbose_name='Категорія'),
        ),
    ]
