# Generated by Django 3.0.5 on 2020-05-03 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200503_1612'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Additional image', 'verbose_name_plural': 'Additional images'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='extra',
        ),
        migrations.AddField(
            model_name='product',
            name='label',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Sale'), (1, 'New'), (2, 'Hot')], null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='main_image',
            field=models.ImageField(blank=True, default='images/not-found.png', upload_to='images/categories/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='collection',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Winter'), (1, 'Summer'), (2, 'Spring/Fall'), (3, 'Multi Season')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Men'), (1, 'Women'), (2, 'Kid')], null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(default='images/not-found.png', upload_to='images/products/main_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=5, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Extra Small'), (1, 'Small'), (2, 'Medium'), (3, 'Large'), (4, 'Extra Large'), (5, 'Two Extra Large')], null=True),
        ),
    ]
