# Generated by Django 3.0.5 on 2020-04-26 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200426_1749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_extra',
            new_name='extra',
        ),
    ]
