# Generated by Django 3.0.5 on 2020-04-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200411_1824'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Додаткова картинка', 'verbose_name_plural': 'Додаткові картинки'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='new_price',
        ),
        migrations.AddField(
            model_name='product',
            name='current_price',
            field=models.PositiveIntegerField(default=100, verbose_name='Поточна ціна'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описання'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(upload_to='images/products/main_images/', verbose_name='Основна картинка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Стара ціна (до знижки)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_extra',
            field=models.CharField(blank=True, choices=[('sale', 'Sale'), ('new', 'New'), ('hot', 'Hot')], max_length=5, verbose_name='Мітка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=5, null=True, verbose_name='Кількість'),
        ),
        migrations.AlterField(
            model_name='product',
            name='season',
            field=models.CharField(choices=[('w', 'Зима'), ('s', 'Літо'), ('s/f', 'Весна/Осінь')], max_length=3, verbose_name='Сезон'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, choices=[('xs', 'Extra Small'), ('s', 'Small'), ('m', 'Medium'), ('l', 'Large'), ('xl', 'Extra Large'), ('xxl', 'Two Extra Large')], max_length=3, verbose_name='Розмір даної одиниці'),
        ),
    ]
