# Generated by Django 3.0.5 on 2020-05-03 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200503_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='main_image',
            field=models.ImageField(blank=True, default=None, upload_to='images/categories/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Men'), (1, 'Women'), (2, 'Kids')], null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(default=None, null=True, upload_to='images/products/main_images/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='images/products/'),
        ),
    ]
