# Generated by Django 3.0.5 on 2020-04-11 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200411_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='season',
            field=models.CharField(choices=[('w', 'Зима'), ('s', 'Літо'), ('s/f', 'Весна/Осінь'), ('mlt', 'Мульти')], max_length=3, verbose_name='Сезон'),
        ),
    ]
