# Generated by Django 3.0.5 on 2020-04-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200426_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='extra',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Sale'), (1, 'New'), (2, 'Hot')], null=True, verbose_name='Мітка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Men'), (1, 'Women'), (2, 'Kids')], null=True, verbose_name='Стать'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Extra Small'), (1, 'Small'), (2, 'Medium'), (3, 'Large'), (4, 'Extra Large'), (5, 'Two Extra Large')], null=True, verbose_name='Розмір даної одиниці'),
        ),
    ]
