# Generated by Django 3.0.5 on 2020-04-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200411_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(default='images/not-found.png', upload_to='images/products/main_images/', verbose_name='Основна картинка'),
        ),
    ]
