# Generated by Django 3.0.5 on 2020-04-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200411_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='main_image',
            field=models.ImageField(blank=True, default='images/not-found.png', upload_to='images/categories/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='current_price',
            field=models.FloatField(verbose_name='Поточна ціна'),
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Стара ціна (до знижки)'),
        ),
    ]
