# Generated by Django 3.0.5 on 2020-04-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_remove_product_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='current_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='season',
        ),
        migrations.AddField(
            model_name='product',
            name='collection',
            field=models.CharField(choices=[('w', 'Winter'), ('s', 'Summer'), ('s/f', 'Spring/Fall'), ('mlt', 'Multi')], default='w', max_length=3, verbose_name='Колекція'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(blank=True, choices=[('men', 'Men'), ('women', 'Women'), ('kids', 'Kids')], max_length=5, verbose_name='Стать'),
        ),
    ]
