# Generated by Django 3.1.4 on 2020-12-24 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0004_auto_20201224_1745'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('del_address', models.CharField(max_length=255)),
                ('del_city', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('new', 'New'), ('preparing', 'Preparing'), ('in_way', 'In Way'), ('delivered', 'Delivered')], default='new', max_length=12)),
                ('items', models.ManyToManyField(related_name='orders', to='product.ProductSize')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
